# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/main_window.ui'
#
# Created: Wed Mar 23 21:23:52 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 952)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_video1 = QtGui.QLabel(self.centralwidget)
        self.label_video1.setGeometry(QtCore.QRect(10, 70, 480, 720))
        self.label_video1.setFrameShape(QtGui.QFrame.Box)
        self.label_video1.setText("")
        self.label_video1.setObjectName("label_video1")
        self.label_video2 = QtGui.QLabel(self.centralwidget)
        self.label_video2.setGeometry(QtCore.QRect(500, 70, 480, 720))
        self.label_video2.setFrameShape(QtGui.QFrame.Box)
        self.label_video2.setText("")
        self.label_video2.setObjectName("label_video2")
        self.slider_video1 = QtGui.QSlider(self.centralwidget)
        self.slider_video1.setGeometry(QtCore.QRect(10, 790, 391, 22))
        self.slider_video1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video1.setObjectName("slider_video1")
        self.slider_video2 = QtGui.QSlider(self.centralwidget)
        self.slider_video2.setGeometry(QtCore.QRect(500, 790, 391, 22))
        self.slider_video2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video2.setObjectName("slider_video2")
        self.label_time_video1 = QtGui.QLabel(self.centralwidget)
        self.label_time_video1.setGeometry(QtCore.QRect(410, 780, 81, 41))
        self.label_time_video1.setObjectName("label_time_video1")
        self.label_time_video2 = QtGui.QLabel(self.centralwidget)
        self.label_time_video2.setGeometry(QtCore.QRect(900, 780, 81, 41))
        self.label_time_video2.setObjectName("label_time_video2")
        self.pushbutton_video2_copy = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_copy.setGeometry(QtCore.QRect(500, 820, 111, 32))
        self.pushbutton_video2_copy.setObjectName("pushbutton_video2_copy")
        self.pushbutton_video1_copy = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_copy.setGeometry(QtCore.QRect(380, 820, 111, 32))
        self.pushbutton_video1_copy.setObjectName("pushbutton_video1_copy")
        self.pushbutton_video1_find = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_find.setGeometry(QtCore.QRect(10, 820, 71, 32))
        self.pushbutton_video1_find.setObjectName("pushbutton_video1_find")
        self.pushbutton_video2_find = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_find.setGeometry(QtCore.QRect(690, 820, 71, 32))
        self.pushbutton_video2_find.setObjectName("pushbutton_video2_find")
        self.pushbutton_video1_playbackward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_playbackward.setGeometry(QtCore.QRect(90, 820, 51, 32))
        self.pushbutton_video1_playbackward.setObjectName("pushbutton_video1_playbackward")
        self.pushbutton_video1_backstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_backstep.setGeometry(QtCore.QRect(130, 820, 51, 32))
        self.pushbutton_video1_backstep.setObjectName("pushbutton_video1_backstep")
        self.pushbutton_video1_forwardstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_forwardstep.setGeometry(QtCore.QRect(210, 820, 51, 32))
        self.pushbutton_video1_forwardstep.setObjectName("pushbutton_video1_forwardstep")
        self.pushbutton_video1_playforward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_playforward.setGeometry(QtCore.QRect(250, 820, 51, 32))
        self.pushbutton_video1_playforward.setObjectName("pushbutton_video1_playforward")
        self.pushbutton_video2_playbackward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_playbackward.setGeometry(QtCore.QRect(770, 820, 51, 32))
        self.pushbutton_video2_playbackward.setObjectName("pushbutton_video2_playbackward")
        self.pushbutton_video2_backstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_backstep.setGeometry(QtCore.QRect(810, 820, 51, 32))
        self.pushbutton_video2_backstep.setObjectName("pushbutton_video2_backstep")
        self.pushbutton_video2_forwardstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_forwardstep.setGeometry(QtCore.QRect(890, 820, 51, 32))
        self.pushbutton_video2_forwardstep.setObjectName("pushbutton_video2_forwardstep")
        self.pushbutton_video2_playforward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_playforward.setGeometry(QtCore.QRect(930, 820, 51, 32))
        self.pushbutton_video2_playforward.setObjectName("pushbutton_video2_playforward")
        self.pushbutton_start = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_start.setGeometry(QtCore.QRect(10, 860, 151, 61))
        self.pushbutton_start.setObjectName("pushbutton_start")
        self.label_speed = QtGui.QLabel(self.centralwidget)
        self.label_speed.setGeometry(QtCore.QRect(670, 870, 311, 41))
        self.label_speed.setStyleSheet("font-size: 30px;")
        self.label_speed.setObjectName("label_speed")
        self.pushbutton_video2_pause = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_pause.setGeometry(QtCore.QRect(850, 820, 51, 32))
        self.pushbutton_video2_pause.setObjectName("pushbutton_video2_pause")
        self.pushbutton_video1_pause = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_pause.setGeometry(QtCore.QRect(170, 820, 51, 32))
        self.pushbutton_video1_pause.setObjectName("pushbutton_video1_pause")
        self.label_video1_online = QtGui.QLabel(self.centralwidget)
        self.label_video1_online.setGeometry(QtCore.QRect(20, 20, 181, 41))
        self.label_video1_online.setStyleSheet("font-size: 20px;")
        self.label_video1_online.setObjectName("label_video1_online")
        self.label_video2_online = QtGui.QLabel(self.centralwidget)
        self.label_video2_online.setGeometry(QtCore.QRect(510, 20, 161, 41))
        self.label_video2_online.setStyleSheet("font-size: 20px;")
        self.label_video2_online.setObjectName("label_video2_online")
        self.pushbutton_stop = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_stop.setGeometry(QtCore.QRect(170, 860, 151, 61))
        self.pushbutton_stop.setObjectName("pushbutton_stop")
        self.lineEdit_distance = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_distance.setGeometry(QtCore.QRect(340, 890, 113, 33))
        self.lineEdit_distance.setObjectName("lineEdit_distance")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 870, 111, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton_video1_align = QtGui.QPushButton(self.centralwidget)
        self.pushButton_video1_align.setGeometry(QtCore.QRect(375, 30, 111, 31))
        self.pushButton_video1_align.setObjectName("pushButton_video1_align")
        self.pushButton_video2_align = QtGui.QPushButton(self.centralwidget)
        self.pushButton_video2_align.setGeometry(QtCore.QRect(860, 30, 111, 31))
        self.pushButton_video2_align.setObjectName("pushButton_video2_align")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_video1.setText(QtGui.QApplication.translate("MainWindow", "00:00.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_video2.setText(QtGui.QApplication.translate("MainWindow", "00:00.000 ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_copy.setText(QtGui.QApplication.translate("MainWindow", "Copy left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_copy.setText(QtGui.QApplication.translate("MainWindow", "Copy right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_find.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_find.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_playbackward.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_backstep.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_forwardstep.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_playforward.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_playbackward.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_backstep.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_forwardstep.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_playforward.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_start.setText(QtGui.QApplication.translate("MainWindow", "Start cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.label_speed.setText(QtGui.QApplication.translate("MainWindow", "Speed: 178.4Kmh", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_pause.setText(QtGui.QApplication.translate("MainWindow", "||", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_pause.setText(QtGui.QApplication.translate("MainWindow", "||", None, QtGui.QApplication.UnicodeUTF8))
        self.label_video1_online.setText(QtGui.QApplication.translate("MainWindow", "Waiting...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_video2_online.setText(QtGui.QApplication.translate("MainWindow", "Waiting...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop Cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Distance meters", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_video1_align.setText(QtGui.QApplication.translate("MainWindow", "Align Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_video2_align.setText(QtGui.QApplication.translate("MainWindow", "Align Camera", None, QtGui.QApplication.UnicodeUTF8))

