# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/main_window.ui'
#
# Created: Wed Apr 13 16:01:29 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1578, 759)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(-1, -1, 12, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_top = QtGui.QHBoxLayout()
        self.horizontalLayout_top.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_top.setObjectName("horizontalLayout_top")
        self.verticalLayout_video_1 = QtGui.QVBoxLayout()
        self.verticalLayout_video_1.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_video_1.setObjectName("verticalLayout_video_1")
        self.horizontalLayout_video_1_top = QtGui.QHBoxLayout()
        self.horizontalLayout_video_1_top.setObjectName("horizontalLayout_video_1_top")
        self.label_video1_online = QtGui.QLabel(self.centralwidget)
        self.label_video1_online.setStyleSheet("font-size: 20px;")
        self.label_video1_online.setObjectName("label_video1_online")
        self.horizontalLayout_video_1_top.addWidget(self.label_video1_online)
        self.pushButton_video1_align = QtGui.QPushButton(self.centralwidget)
        self.pushButton_video1_align.setObjectName("pushButton_video1_align")
        self.horizontalLayout_video_1_top.addWidget(self.pushButton_video1_align)
        self.horizontalLayout_video_1_top.setStretch(0, 1)
        self.verticalLayout_video_1.addLayout(self.horizontalLayout_video_1_top)
        self.label_video1 = QtGui.QLabel(self.centralwidget)
        self.label_video1.setFrameShape(QtGui.QFrame.Box)
        self.label_video1.setText("")
        self.label_video1.setScaledContents(True)
        self.label_video1.setObjectName("label_video1")
        self.verticalLayout_video_1.addWidget(self.label_video1)
        self.horizontalLayout_video_1_slider = QtGui.QHBoxLayout()
        self.horizontalLayout_video_1_slider.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_video_1_slider.setObjectName("horizontalLayout_video_1_slider")
        self.slider_video1 = QtGui.QSlider(self.centralwidget)
        self.slider_video1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video1.setObjectName("slider_video1")
        self.horizontalLayout_video_1_slider.addWidget(self.slider_video1)
        self.label_time_video1 = QtGui.QLabel(self.centralwidget)
        self.label_time_video1.setObjectName("label_time_video1")
        self.horizontalLayout_video_1_slider.addWidget(self.label_time_video1)
        self.verticalLayout_video_1.addLayout(self.horizontalLayout_video_1_slider)
        self.horizontalLayout_video_1_buttons = QtGui.QHBoxLayout()
        self.horizontalLayout_video_1_buttons.setSpacing(0)
        self.horizontalLayout_video_1_buttons.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_video_1_buttons.setObjectName("horizontalLayout_video_1_buttons")
        self.pushbutton_video1_find = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_find.setObjectName("pushbutton_video1_find")
        self.horizontalLayout_video_1_buttons.addWidget(self.pushbutton_video1_find)
        spacerItem = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_video_1_buttons.addItem(spacerItem)
        self.pushbutton_video1_playbackward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_playbackward.setObjectName("pushbutton_video1_playbackward")
        self.horizontalLayout_video_1_buttons.addWidget(self.pushbutton_video1_playbackward)
        self.pushbutton_video1_backstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_backstep.setObjectName("pushbutton_video1_backstep")
        self.horizontalLayout_video_1_buttons.addWidget(self.pushbutton_video1_backstep)
        self.pushbutton_video1_pause = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_pause.setObjectName("pushbutton_video1_pause")
        self.horizontalLayout_video_1_buttons.addWidget(self.pushbutton_video1_pause)
        self.pushbutton_video1_forwardstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_forwardstep.setObjectName("pushbutton_video1_forwardstep")
        self.horizontalLayout_video_1_buttons.addWidget(self.pushbutton_video1_forwardstep)
        self.pushbutton_video1_playforward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_playforward.setObjectName("pushbutton_video1_playforward")
        self.horizontalLayout_video_1_buttons.addWidget(self.pushbutton_video1_playforward)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_video_1_buttons.addItem(spacerItem1)
        self.pushbutton_video1_copy = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_copy.setObjectName("pushbutton_video1_copy")
        self.horizontalLayout_video_1_buttons.addWidget(self.pushbutton_video1_copy)
        self.horizontalLayout_video_1_buttons.setStretch(7, 1)
        self.verticalLayout_video_1.addLayout(self.horizontalLayout_video_1_buttons)
        self.verticalLayout_video_1.setStretch(1, 1)
        self.horizontalLayout_top.addLayout(self.verticalLayout_video_1)
        self.verticalLayout_groundlevel = QtGui.QVBoxLayout()
        self.verticalLayout_groundlevel.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_groundlevel.setObjectName("verticalLayout_groundlevel")
        spacerItem2 = QtGui.QSpacerItem(1, 34, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_groundlevel.addItem(spacerItem2)
        self.verticalSlider_groundlevel = QtGui.QSlider(self.centralwidget)
        self.verticalSlider_groundlevel.setMinimum(1)
        self.verticalSlider_groundlevel.setMaximum(480)
        self.verticalSlider_groundlevel.setProperty("value", 400)
        self.verticalSlider_groundlevel.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_groundlevel.setInvertedAppearance(True)
        self.verticalSlider_groundlevel.setObjectName("verticalSlider_groundlevel")
        self.verticalLayout_groundlevel.addWidget(self.verticalSlider_groundlevel)
        spacerItem3 = QtGui.QSpacerItem(1, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_groundlevel.addItem(spacerItem3)
        self.horizontalLayout_top.addLayout(self.verticalLayout_groundlevel)
        self.verticalLayout_video_2 = QtGui.QVBoxLayout()
        self.verticalLayout_video_2.setObjectName("verticalLayout_video_2")
        self.horizontalLayout_video_2_top = QtGui.QHBoxLayout()
        self.horizontalLayout_video_2_top.setObjectName("horizontalLayout_video_2_top")
        self.label_video2_online = QtGui.QLabel(self.centralwidget)
        self.label_video2_online.setStyleSheet("font-size: 20px;")
        self.label_video2_online.setObjectName("label_video2_online")
        self.horizontalLayout_video_2_top.addWidget(self.label_video2_online)
        self.pushButton_video2_align = QtGui.QPushButton(self.centralwidget)
        self.pushButton_video2_align.setObjectName("pushButton_video2_align")
        self.horizontalLayout_video_2_top.addWidget(self.pushButton_video2_align)
        self.horizontalLayout_video_2_top.setStretch(0, 1)
        self.verticalLayout_video_2.addLayout(self.horizontalLayout_video_2_top)
        self.label_video2 = QtGui.QLabel(self.centralwidget)
        self.label_video2.setFrameShape(QtGui.QFrame.Box)
        self.label_video2.setText("")
        self.label_video2.setScaledContents(True)
        self.label_video2.setObjectName("label_video2")
        self.verticalLayout_video_2.addWidget(self.label_video2)
        self.horizontalLayout_video_2_slider = QtGui.QHBoxLayout()
        self.horizontalLayout_video_2_slider.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_video_2_slider.setObjectName("horizontalLayout_video_2_slider")
        self.slider_video2 = QtGui.QSlider(self.centralwidget)
        self.slider_video2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video2.setObjectName("slider_video2")
        self.horizontalLayout_video_2_slider.addWidget(self.slider_video2)
        self.label_time_video2 = QtGui.QLabel(self.centralwidget)
        self.label_time_video2.setObjectName("label_time_video2")
        self.horizontalLayout_video_2_slider.addWidget(self.label_time_video2)
        self.verticalLayout_video_2.addLayout(self.horizontalLayout_video_2_slider)
        self.horizontalLayout_video_2_buttons = QtGui.QHBoxLayout()
        self.horizontalLayout_video_2_buttons.setSpacing(0)
        self.horizontalLayout_video_2_buttons.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_video_2_buttons.setObjectName("horizontalLayout_video_2_buttons")
        self.pushbutton_video2_copy = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_copy.setObjectName("pushbutton_video2_copy")
        self.horizontalLayout_video_2_buttons.addWidget(self.pushbutton_video2_copy)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_video_2_buttons.addItem(spacerItem4)
        self.pushbutton_video2_find = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_find.setObjectName("pushbutton_video2_find")
        self.horizontalLayout_video_2_buttons.addWidget(self.pushbutton_video2_find)
        spacerItem5 = QtGui.QSpacerItem(16, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_video_2_buttons.addItem(spacerItem5)
        self.pushbutton_video2_playbackward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_playbackward.setObjectName("pushbutton_video2_playbackward")
        self.horizontalLayout_video_2_buttons.addWidget(self.pushbutton_video2_playbackward)
        self.pushbutton_video2_backstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_backstep.setObjectName("pushbutton_video2_backstep")
        self.horizontalLayout_video_2_buttons.addWidget(self.pushbutton_video2_backstep)
        self.pushbutton_video2_pause = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_pause.setObjectName("pushbutton_video2_pause")
        self.horizontalLayout_video_2_buttons.addWidget(self.pushbutton_video2_pause)
        self.pushbutton_video2_forwardstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_forwardstep.setObjectName("pushbutton_video2_forwardstep")
        self.horizontalLayout_video_2_buttons.addWidget(self.pushbutton_video2_forwardstep)
        self.pushbutton_video2_playforward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_playforward.setObjectName("pushbutton_video2_playforward")
        self.horizontalLayout_video_2_buttons.addWidget(self.pushbutton_video2_playforward)
        self.horizontalLayout_video_2_buttons.setStretch(1, 1)
        self.verticalLayout_video_2.addLayout(self.horizontalLayout_video_2_buttons)
        self.verticalLayout_video_2.setStretch(1, 1)
        self.horizontalLayout_top.addLayout(self.verticalLayout_video_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem6 = QtGui.QSpacerItem(280, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.label_distance = QtGui.QLabel(self.centralwidget)
        self.label_distance.setObjectName("label_distance")
        self.verticalLayout_4.addWidget(self.label_distance)
        self.lineEdit_distance = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_distance.setObjectName("lineEdit_distance")
        self.verticalLayout_4.addWidget(self.lineEdit_distance)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_motion_track = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_motion_track.sizePolicy().hasHeightForWidth())
        self.checkBox_motion_track.setSizePolicy(sizePolicy)
        self.checkBox_motion_track.setObjectName("checkBox_motion_track")
        self.horizontalLayout_3.addWidget(self.checkBox_motion_track)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.listView_anouncements = QtGui.QListView(self.centralwidget)
        self.listView_anouncements.setMinimumSize(QtCore.QSize(0, 300))
        self.listView_anouncements.setMaximumSize(QtCore.QSize(16777215, 400))
        self.listView_anouncements.setObjectName("listView_anouncements")
        self.verticalLayout_4.addWidget(self.listView_anouncements)
        spacerItem7 = QtGui.QSpacerItem(280, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.label_flightnumber = QtGui.QLabel(self.centralwidget)
        self.label_flightnumber.setObjectName("label_flightnumber")
        self.verticalLayout_4.addWidget(self.label_flightnumber)
        self.gridLayout_flights = QtGui.QGridLayout()
        self.gridLayout_flights.setHorizontalSpacing(6)
        self.gridLayout_flights.setVerticalSpacing(15)
        self.gridLayout_flights.setObjectName("gridLayout_flights")
        self.radioButton_flight_7 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_7.setObjectName("radioButton_flight_7")
        self.gridLayout_flights.addWidget(self.radioButton_flight_7, 2, 1, 1, 1)
        self.radioButton_flight_1 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_1.setObjectName("radioButton_flight_1")
        self.gridLayout_flights.addWidget(self.radioButton_flight_1, 1, 0, 1, 1)
        self.radioButton_flight_15 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_15.setObjectName("radioButton_flight_15")
        self.gridLayout_flights.addWidget(self.radioButton_flight_15, 3, 4, 1, 1)
        self.radioButton_flight_16 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_16.setObjectName("radioButton_flight_16")
        self.gridLayout_flights.addWidget(self.radioButton_flight_16, 4, 0, 1, 1)
        self.radioButton_flight_9 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_9.setObjectName("radioButton_flight_9")
        self.gridLayout_flights.addWidget(self.radioButton_flight_9, 2, 3, 1, 1)
        self.radioButton_flight_19 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_19.setObjectName("radioButton_flight_19")
        self.gridLayout_flights.addWidget(self.radioButton_flight_19, 4, 3, 1, 1)
        self.radioButton_flight_17 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_17.setObjectName("radioButton_flight_17")
        self.gridLayout_flights.addWidget(self.radioButton_flight_17, 4, 1, 1, 1)
        self.radioButton_flight_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_5.setObjectName("radioButton_flight_5")
        self.gridLayout_flights.addWidget(self.radioButton_flight_5, 1, 4, 1, 1)
        self.radioButton_flight_11 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_11.setObjectName("radioButton_flight_11")
        self.gridLayout_flights.addWidget(self.radioButton_flight_11, 3, 0, 1, 1)
        self.radioButton_flight_6 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_6.setObjectName("radioButton_flight_6")
        self.gridLayout_flights.addWidget(self.radioButton_flight_6, 2, 0, 1, 1)
        self.radioButton_flight_20 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_20.setObjectName("radioButton_flight_20")
        self.gridLayout_flights.addWidget(self.radioButton_flight_20, 4, 4, 1, 1)
        self.radioButton_flight_4 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_4.setObjectName("radioButton_flight_4")
        self.gridLayout_flights.addWidget(self.radioButton_flight_4, 1, 3, 1, 1)
        self.radioButton_flight_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_3.setObjectName("radioButton_flight_3")
        self.gridLayout_flights.addWidget(self.radioButton_flight_3, 1, 2, 1, 1)
        self.radioButton_flight_18 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_18.setObjectName("radioButton_flight_18")
        self.gridLayout_flights.addWidget(self.radioButton_flight_18, 4, 2, 1, 1)
        self.radioButton_flight_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_2.setObjectName("radioButton_flight_2")
        self.gridLayout_flights.addWidget(self.radioButton_flight_2, 1, 1, 1, 1)
        self.radioButton_flight_14 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_14.setObjectName("radioButton_flight_14")
        self.gridLayout_flights.addWidget(self.radioButton_flight_14, 3, 3, 1, 1)
        self.radioButton_flight_13 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_13.setObjectName("radioButton_flight_13")
        self.gridLayout_flights.addWidget(self.radioButton_flight_13, 3, 2, 1, 1)
        self.radioButton_flight_12 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_12.setObjectName("radioButton_flight_12")
        self.gridLayout_flights.addWidget(self.radioButton_flight_12, 3, 1, 1, 1)
        self.radioButton_flight_10 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_10.setObjectName("radioButton_flight_10")
        self.gridLayout_flights.addWidget(self.radioButton_flight_10, 2, 4, 1, 1)
        self.radioButton_flight_8 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_8.setObjectName("radioButton_flight_8")
        self.gridLayout_flights.addWidget(self.radioButton_flight_8, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_flights)
        spacerItem8 = QtGui.QSpacerItem(20, 80, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.verticalLayout_4.setStretch(8, 1)
        self.horizontalLayout_top.addLayout(self.verticalLayout_4)
        self.horizontalLayout_top.setStretch(0, 1)
        self.horizontalLayout_top.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_top)
        self.horizontalLayout_bottom = QtGui.QHBoxLayout()
        self.horizontalLayout_bottom.setContentsMargins(0, 0, -1, 1)
        self.horizontalLayout_bottom.setObjectName("horizontalLayout_bottom")
        self.pushbutton_start = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_start.setMinimumSize(QtCore.QSize(0, 60))
        self.pushbutton_start.setBaseSize(QtCore.QSize(0, 0))
        self.pushbutton_start.setObjectName("pushbutton_start")
        self.horizontalLayout_bottom.addWidget(self.pushbutton_start)
        self.pushbutton_stop = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_stop.setMinimumSize(QtCore.QSize(0, 60))
        self.pushbutton_stop.setObjectName("pushbutton_stop")
        self.horizontalLayout_bottom.addWidget(self.pushbutton_stop)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 20, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_speed_label = QtGui.QLabel(self.centralwidget)
        self.label_speed_label.setStyleSheet("font-size: 24px;")
        self.label_speed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_speed_label.setObjectName("label_speed_label")
        self.gridLayout.addWidget(self.label_speed_label, 1, 0, 1, 1)
        self.label_time = QtGui.QLabel(self.centralwidget)
        self.label_time.setStyleSheet("font-size: 24px;")
        self.label_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.gridLayout.addWidget(self.label_time, 0, 1, 1, 1)
        self.label_time_label = QtGui.QLabel(self.centralwidget)
        self.label_time_label.setStyleSheet("font-size: 24px;")
        self.label_time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time_label.setObjectName("label_time_label")
        self.gridLayout.addWidget(self.label_time_label, 0, 0, 1, 1)
        self.label_speed = QtGui.QLabel(self.centralwidget)
        self.label_speed.setStyleSheet("font-size: 24px;")
        self.label_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout.addWidget(self.label_speed, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.horizontalLayout_bottom.addLayout(self.gridLayout)
        spacerItem9 = QtGui.QSpacerItem(280, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_bottom.addItem(spacerItem9)
        self.horizontalLayout_bottom.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_bottom)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_video1_online.setText(QtGui.QApplication.translate("MainWindow", "Waiting...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_video1_align.setText(QtGui.QApplication.translate("MainWindow", "Align Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_video1.setText(QtGui.QApplication.translate("MainWindow", "00:00.000", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_find.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_playbackward.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_backstep.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_pause.setText(QtGui.QApplication.translate("MainWindow", "||", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_forwardstep.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_playforward.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_copy.setText(QtGui.QApplication.translate("MainWindow", "Copy right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_video2_online.setText(QtGui.QApplication.translate("MainWindow", "Waiting...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_video2_align.setText(QtGui.QApplication.translate("MainWindow", "Align Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_video2.setText(QtGui.QApplication.translate("MainWindow", "00:00.000 ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_copy.setText(QtGui.QApplication.translate("MainWindow", "Copy left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_find.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_playbackward.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_backstep.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_pause.setText(QtGui.QApplication.translate("MainWindow", "||", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_forwardstep.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_playforward.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_distance.setText(QtGui.QApplication.translate("MainWindow", "Distance meters", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_motion_track.setText(QtGui.QApplication.translate("MainWindow", "Realtime Anouncements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flightnumber.setText(QtGui.QApplication.translate("MainWindow", "Flight number", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_15.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_16.setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_19.setText(QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_17.setText(QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_11.setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_20.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_18.setText(QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_14.setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_13.setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_12.setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_10.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_flight_8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_start.setText(QtGui.QApplication.translate("MainWindow", "Start cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop Cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.label_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time.setText(QtGui.QApplication.translate("MainWindow", "1.423 sec", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_label.setText(QtGui.QApplication.translate("MainWindow", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_speed.setText(QtGui.QApplication.translate("MainWindow", "888.88 kmh", None, QtGui.QApplication.UnicodeUTF8))

