# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtui/main_window.ui'
#
# Created: Fri Apr  1 19:46:55 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 1036)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_video1 = QtGui.QLabel(self.centralwidget)
        self.label_video1.setGeometry(QtCore.QRect(10, 70, 480, 720))
        self.label_video1.setFrameShape(QtGui.QFrame.Box)
        self.label_video1.setText("")
        self.label_video1.setObjectName("label_video1")
        self.label_video2 = QtGui.QLabel(self.centralwidget)
        self.label_video2.setGeometry(QtCore.QRect(500, 70, 480, 720))
        self.label_video2.setFrameShape(QtGui.QFrame.Box)
        self.label_video2.setText("")
        self.label_video2.setObjectName("label_video2")
        self.slider_video1 = QtGui.QSlider(self.centralwidget)
        self.slider_video1.setGeometry(QtCore.QRect(10, 790, 391, 22))
        self.slider_video1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video1.setObjectName("slider_video1")
        self.slider_video2 = QtGui.QSlider(self.centralwidget)
        self.slider_video2.setGeometry(QtCore.QRect(500, 790, 391, 22))
        self.slider_video2.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video2.setObjectName("slider_video2")
        self.label_time_video1 = QtGui.QLabel(self.centralwidget)
        self.label_time_video1.setGeometry(QtCore.QRect(410, 780, 81, 41))
        self.label_time_video1.setObjectName("label_time_video1")
        self.label_time_video2 = QtGui.QLabel(self.centralwidget)
        self.label_time_video2.setGeometry(QtCore.QRect(900, 780, 81, 41))
        self.label_time_video2.setObjectName("label_time_video2")
        self.pushbutton_video2_copy = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_copy.setGeometry(QtCore.QRect(500, 820, 111, 32))
        self.pushbutton_video2_copy.setObjectName("pushbutton_video2_copy")
        self.pushbutton_video1_copy = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_copy.setGeometry(QtCore.QRect(380, 820, 111, 32))
        self.pushbutton_video1_copy.setObjectName("pushbutton_video1_copy")
        self.pushbutton_video1_find = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_find.setGeometry(QtCore.QRect(10, 820, 71, 32))
        self.pushbutton_video1_find.setObjectName("pushbutton_video1_find")
        self.pushbutton_video2_find = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_find.setGeometry(QtCore.QRect(690, 820, 71, 32))
        self.pushbutton_video2_find.setObjectName("pushbutton_video2_find")
        self.pushbutton_video1_playbackward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_playbackward.setGeometry(QtCore.QRect(90, 820, 51, 32))
        self.pushbutton_video1_playbackward.setObjectName("pushbutton_video1_playbackward")
        self.pushbutton_video1_backstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_backstep.setGeometry(QtCore.QRect(130, 820, 51, 32))
        self.pushbutton_video1_backstep.setObjectName("pushbutton_video1_backstep")
        self.pushbutton_video1_forwardstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_forwardstep.setGeometry(QtCore.QRect(210, 820, 51, 32))
        self.pushbutton_video1_forwardstep.setObjectName("pushbutton_video1_forwardstep")
        self.pushbutton_video1_playforward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_playforward.setGeometry(QtCore.QRect(250, 820, 51, 32))
        self.pushbutton_video1_playforward.setObjectName("pushbutton_video1_playforward")
        self.pushbutton_video2_playbackward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_playbackward.setGeometry(QtCore.QRect(770, 820, 51, 32))
        self.pushbutton_video2_playbackward.setObjectName("pushbutton_video2_playbackward")
        self.pushbutton_video2_backstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_backstep.setGeometry(QtCore.QRect(810, 820, 51, 32))
        self.pushbutton_video2_backstep.setObjectName("pushbutton_video2_backstep")
        self.pushbutton_video2_forwardstep = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_forwardstep.setGeometry(QtCore.QRect(890, 820, 51, 32))
        self.pushbutton_video2_forwardstep.setObjectName("pushbutton_video2_forwardstep")
        self.pushbutton_video2_playforward = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_playforward.setGeometry(QtCore.QRect(930, 820, 51, 32))
        self.pushbutton_video2_playforward.setObjectName("pushbutton_video2_playforward")
        self.pushbutton_start = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_start.setGeometry(QtCore.QRect(10, 860, 151, 61))
        self.pushbutton_start.setObjectName("pushbutton_start")
        self.label_speed_label = QtGui.QLabel(self.centralwidget)
        self.label_speed_label.setGeometry(QtCore.QRect(740, 870, 81, 31))
        self.label_speed_label.setStyleSheet("font-size: 24px;")
        self.label_speed_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_speed_label.setObjectName("label_speed_label")
        self.pushbutton_video2_pause = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video2_pause.setGeometry(QtCore.QRect(850, 820, 51, 32))
        self.pushbutton_video2_pause.setObjectName("pushbutton_video2_pause")
        self.pushbutton_video1_pause = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_video1_pause.setGeometry(QtCore.QRect(170, 820, 51, 32))
        self.pushbutton_video1_pause.setObjectName("pushbutton_video1_pause")
        self.label_video1_online = QtGui.QLabel(self.centralwidget)
        self.label_video1_online.setGeometry(QtCore.QRect(20, 20, 181, 41))
        self.label_video1_online.setStyleSheet("font-size: 20px;")
        self.label_video1_online.setObjectName("label_video1_online")
        self.label_video2_online = QtGui.QLabel(self.centralwidget)
        self.label_video2_online.setGeometry(QtCore.QRect(510, 20, 161, 41))
        self.label_video2_online.setStyleSheet("font-size: 20px;")
        self.label_video2_online.setObjectName("label_video2_online")
        self.pushbutton_stop = QtGui.QPushButton(self.centralwidget)
        self.pushbutton_stop.setGeometry(QtCore.QRect(170, 860, 151, 61))
        self.pushbutton_stop.setObjectName("pushbutton_stop")
        self.lineEdit_distance = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_distance.setGeometry(QtCore.QRect(340, 890, 113, 33))
        self.lineEdit_distance.setObjectName("lineEdit_distance")
        self.label_distance = QtGui.QLabel(self.centralwidget)
        self.label_distance.setGeometry(QtCore.QRect(340, 870, 111, 21))
        self.label_distance.setObjectName("label_distance")
        self.pushButton_video1_align = QtGui.QPushButton(self.centralwidget)
        self.pushButton_video1_align.setGeometry(QtCore.QRect(375, 30, 111, 31))
        self.pushButton_video1_align.setObjectName("pushButton_video1_align")
        self.pushButton_video2_align = QtGui.QPushButton(self.centralwidget)
        self.pushButton_video2_align.setGeometry(QtCore.QRect(860, 30, 111, 31))
        self.pushButton_video2_align.setObjectName("pushButton_video2_align")
        self.radioButton_flight_1 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_1.setGeometry(QtCore.QRect(100, 960, 21, 26))
        self.radioButton_flight_1.setText("")
        self.radioButton_flight_1.setObjectName("radioButton_flight_1")
        self.radioButton_flight_2 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_2.setGeometry(QtCore.QRect(140, 960, 21, 26))
        self.radioButton_flight_2.setText("")
        self.radioButton_flight_2.setObjectName("radioButton_flight_2")
        self.radioButton_flight_3 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_3.setGeometry(QtCore.QRect(180, 960, 21, 26))
        self.radioButton_flight_3.setText("")
        self.radioButton_flight_3.setObjectName("radioButton_flight_3")
        self.radioButton_flight_5 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_5.setGeometry(QtCore.QRect(260, 960, 21, 26))
        self.radioButton_flight_5.setText("")
        self.radioButton_flight_5.setObjectName("radioButton_flight_5")
        self.radioButton_flight_6 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_6.setGeometry(QtCore.QRect(300, 960, 21, 26))
        self.radioButton_flight_6.setText("")
        self.radioButton_flight_6.setObjectName("radioButton_flight_6")
        self.radioButton_flight_7 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_7.setGeometry(QtCore.QRect(340, 960, 21, 26))
        self.radioButton_flight_7.setText("")
        self.radioButton_flight_7.setObjectName("radioButton_flight_7")
        self.radioButton_flight_8 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_8.setGeometry(QtCore.QRect(380, 960, 21, 26))
        self.radioButton_flight_8.setText("")
        self.radioButton_flight_8.setObjectName("radioButton_flight_8")
        self.radioButton_flight_9 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_9.setGeometry(QtCore.QRect(420, 960, 21, 26))
        self.radioButton_flight_9.setText("")
        self.radioButton_flight_9.setObjectName("radioButton_flight_9")
        self.radioButton_flight_10 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_10.setGeometry(QtCore.QRect(460, 960, 21, 26))
        self.radioButton_flight_10.setText("")
        self.radioButton_flight_10.setObjectName("radioButton_flight_10")
        self.radioButton_flight_11 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_11.setGeometry(QtCore.QRect(500, 960, 21, 26))
        self.radioButton_flight_11.setText("")
        self.radioButton_flight_11.setObjectName("radioButton_flight_11")
        self.radioButton_flight_12 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_12.setGeometry(QtCore.QRect(540, 960, 21, 26))
        self.radioButton_flight_12.setText("")
        self.radioButton_flight_12.setObjectName("radioButton_flight_12")
        self.radioButton_flight_13 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_13.setGeometry(QtCore.QRect(580, 960, 21, 26))
        self.radioButton_flight_13.setText("")
        self.radioButton_flight_13.setObjectName("radioButton_flight_13")
        self.radioButton_flight_14 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_14.setGeometry(QtCore.QRect(620, 960, 21, 26))
        self.radioButton_flight_14.setText("")
        self.radioButton_flight_14.setObjectName("radioButton_flight_14")
        self.radioButton_flight_15 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_15.setGeometry(QtCore.QRect(660, 960, 21, 26))
        self.radioButton_flight_15.setText("")
        self.radioButton_flight_15.setObjectName("radioButton_flight_15")
        self.radioButton_flight_16 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_16.setGeometry(QtCore.QRect(700, 960, 21, 26))
        self.radioButton_flight_16.setText("")
        self.radioButton_flight_16.setObjectName("radioButton_flight_16")
        self.radioButton_flight_17 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_17.setGeometry(QtCore.QRect(740, 960, 21, 26))
        self.radioButton_flight_17.setText("")
        self.radioButton_flight_17.setObjectName("radioButton_flight_17")
        self.radioButton_flight_18 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_18.setGeometry(QtCore.QRect(780, 960, 21, 26))
        self.radioButton_flight_18.setText("")
        self.radioButton_flight_18.setObjectName("radioButton_flight_18")
        self.radioButton_flight_19 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_19.setGeometry(QtCore.QRect(820, 960, 21, 26))
        self.radioButton_flight_19.setText("")
        self.radioButton_flight_19.setObjectName("radioButton_flight_19")
        self.radioButton_flight_20 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_20.setGeometry(QtCore.QRect(860, 960, 21, 26))
        self.radioButton_flight_20.setText("")
        self.radioButton_flight_20.setObjectName("radioButton_flight_20")
        self.label_flight_1 = QtGui.QLabel(self.centralwidget)
        self.label_flight_1.setGeometry(QtCore.QRect(100, 980, 21, 21))
        self.label_flight_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_1.setObjectName("label_flight_1")
        self.label_flight_2 = QtGui.QLabel(self.centralwidget)
        self.label_flight_2.setGeometry(QtCore.QRect(140, 980, 21, 21))
        self.label_flight_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_2.setObjectName("label_flight_2")
        self.label_flight_3 = QtGui.QLabel(self.centralwidget)
        self.label_flight_3.setGeometry(QtCore.QRect(180, 980, 21, 21))
        self.label_flight_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_3.setObjectName("label_flight_3")
        self.label_flight_4 = QtGui.QLabel(self.centralwidget)
        self.label_flight_4.setGeometry(QtCore.QRect(220, 980, 21, 21))
        self.label_flight_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_4.setObjectName("label_flight_4")
        self.label_flight_5 = QtGui.QLabel(self.centralwidget)
        self.label_flight_5.setGeometry(QtCore.QRect(260, 980, 21, 21))
        self.label_flight_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_5.setObjectName("label_flight_5")
        self.label_flight_6 = QtGui.QLabel(self.centralwidget)
        self.label_flight_6.setGeometry(QtCore.QRect(300, 980, 21, 21))
        self.label_flight_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_6.setObjectName("label_flight_6")
        self.label_flight_7 = QtGui.QLabel(self.centralwidget)
        self.label_flight_7.setGeometry(QtCore.QRect(340, 980, 21, 21))
        self.label_flight_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_7.setObjectName("label_flight_7")
        self.label_flight_8 = QtGui.QLabel(self.centralwidget)
        self.label_flight_8.setGeometry(QtCore.QRect(380, 980, 21, 21))
        self.label_flight_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_8.setObjectName("label_flight_8")
        self.label_flight_9 = QtGui.QLabel(self.centralwidget)
        self.label_flight_9.setGeometry(QtCore.QRect(420, 980, 21, 21))
        self.label_flight_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_9.setObjectName("label_flight_9")
        self.label_flight_10 = QtGui.QLabel(self.centralwidget)
        self.label_flight_10.setGeometry(QtCore.QRect(460, 980, 21, 21))
        self.label_flight_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_10.setObjectName("label_flight_10")
        self.label_flight_11 = QtGui.QLabel(self.centralwidget)
        self.label_flight_11.setGeometry(QtCore.QRect(500, 980, 21, 21))
        self.label_flight_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_11.setObjectName("label_flight_11")
        self.label_flight_12 = QtGui.QLabel(self.centralwidget)
        self.label_flight_12.setGeometry(QtCore.QRect(540, 980, 21, 21))
        self.label_flight_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_12.setObjectName("label_flight_12")
        self.label_flight_13 = QtGui.QLabel(self.centralwidget)
        self.label_flight_13.setGeometry(QtCore.QRect(580, 980, 21, 21))
        self.label_flight_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_13.setObjectName("label_flight_13")
        self.label_flight_14 = QtGui.QLabel(self.centralwidget)
        self.label_flight_14.setGeometry(QtCore.QRect(620, 980, 21, 21))
        self.label_flight_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_14.setObjectName("label_flight_14")
        self.label_flight_15 = QtGui.QLabel(self.centralwidget)
        self.label_flight_15.setGeometry(QtCore.QRect(660, 980, 21, 21))
        self.label_flight_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_15.setObjectName("label_flight_15")
        self.label_flight_16 = QtGui.QLabel(self.centralwidget)
        self.label_flight_16.setGeometry(QtCore.QRect(700, 980, 21, 21))
        self.label_flight_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_16.setObjectName("label_flight_16")
        self.label_flight_17 = QtGui.QLabel(self.centralwidget)
        self.label_flight_17.setGeometry(QtCore.QRect(740, 980, 21, 21))
        self.label_flight_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_17.setObjectName("label_flight_17")
        self.label_flight_18 = QtGui.QLabel(self.centralwidget)
        self.label_flight_18.setGeometry(QtCore.QRect(780, 980, 21, 21))
        self.label_flight_18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_18.setObjectName("label_flight_18")
        self.label_flight_19 = QtGui.QLabel(self.centralwidget)
        self.label_flight_19.setGeometry(QtCore.QRect(820, 980, 21, 21))
        self.label_flight_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_19.setObjectName("label_flight_19")
        self.label_flight_20 = QtGui.QLabel(self.centralwidget)
        self.label_flight_20.setGeometry(QtCore.QRect(860, 980, 21, 21))
        self.label_flight_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_flight_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_flight_20.setObjectName("label_flight_20")
        self.radioButton_flight_4 = QtGui.QRadioButton(self.centralwidget)
        self.radioButton_flight_4.setGeometry(QtCore.QRect(220, 960, 21, 26))
        self.radioButton_flight_4.setText("")
        self.radioButton_flight_4.setObjectName("radioButton_flight_4")
        self.label_time_label = QtGui.QLabel(self.centralwidget)
        self.label_time_label.setGeometry(QtCore.QRect(740, 910, 81, 31))
        self.label_time_label.setStyleSheet("font-size: 24px;")
        self.label_time_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_time_label.setObjectName("label_time_label")
        self.label_speed = QtGui.QLabel(self.centralwidget)
        self.label_speed.setGeometry(QtCore.QRect(840, 870, 141, 31))
        self.label_speed.setStyleSheet("font-size: 24px;")
        self.label_speed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_speed.setObjectName("label_speed")
        self.label_time = QtGui.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(840, 910, 141, 31))
        self.label_time.setStyleSheet("font-size: 24px;")
        self.label_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_time.setObjectName("label_time")
        self.checkBox_motion_track = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_motion_track.setGeometry(QtCore.QRect(480, 890, 191, 26))
        self.checkBox_motion_track.setObjectName("checkBox_motion_track")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_video1.setText(QtGui.QApplication.translate("MainWindow", "00:00.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_video2.setText(QtGui.QApplication.translate("MainWindow", "00:00.000 ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_copy.setText(QtGui.QApplication.translate("MainWindow", "Copy left", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_copy.setText(QtGui.QApplication.translate("MainWindow", "Copy right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_find.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_find.setText(QtGui.QApplication.translate("MainWindow", "Find", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_playbackward.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_backstep.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_forwardstep.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_playforward.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_playbackward.setText(QtGui.QApplication.translate("MainWindow", "<<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_backstep.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_forwardstep.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_playforward.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_start.setText(QtGui.QApplication.translate("MainWindow", "Start cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.label_speed_label.setText(QtGui.QApplication.translate("MainWindow", "Speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video2_pause.setText(QtGui.QApplication.translate("MainWindow", "||", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_video1_pause.setText(QtGui.QApplication.translate("MainWindow", "||", None, QtGui.QApplication.UnicodeUTF8))
        self.label_video1_online.setText(QtGui.QApplication.translate("MainWindow", "Waiting...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_video2_online.setText(QtGui.QApplication.translate("MainWindow", "Waiting...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushbutton_stop.setText(QtGui.QApplication.translate("MainWindow", "Stop Cameras", None, QtGui.QApplication.UnicodeUTF8))
        self.label_distance.setText(QtGui.QApplication.translate("MainWindow", "Distance meters", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_video1_align.setText(QtGui.QApplication.translate("MainWindow", "Align Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_video2_align.setText(QtGui.QApplication.translate("MainWindow", "Align Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_10.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_11.setText(QtGui.QApplication.translate("MainWindow", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_12.setText(QtGui.QApplication.translate("MainWindow", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_13.setText(QtGui.QApplication.translate("MainWindow", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_14.setText(QtGui.QApplication.translate("MainWindow", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_15.setText(QtGui.QApplication.translate("MainWindow", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_16.setText(QtGui.QApplication.translate("MainWindow", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_17.setText(QtGui.QApplication.translate("MainWindow", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_18.setText(QtGui.QApplication.translate("MainWindow", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_19.setText(QtGui.QApplication.translate("MainWindow", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.label_flight_20.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time_label.setText(QtGui.QApplication.translate("MainWindow", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_speed.setText(QtGui.QApplication.translate("MainWindow", "888.88 kmh", None, QtGui.QApplication.UnicodeUTF8))
        self.label_time.setText(QtGui.QApplication.translate("MainWindow", "1.423 sec", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_motion_track.setText(QtGui.QApplication.translate("MainWindow", "Realtime Anouncements", None, QtGui.QApplication.UnicodeUTF8))

