#!/bin/bash

echo "Compiling sleipnir.c"
gcc -c sleipnir.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
if [ $? -ne 0 ]
then
   echo "Error Compiling, abort!"
   exit 1
fi

echo "Compiling RaspiCamControl.c"
gcc -c RaspiCamControl.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
if [ $? -ne 0 ]
then
   echo "Error Compiling, abort!"
   exit 1
fi

echo "Compiling RaspiCLI.c"
gcc -c RaspiCLI.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
if [ $? -ne 0 ]
then
   echo "Error Compiling, abort!"
   exit 1
fi

echo "Compiling jpegs.c"
gcc -c jpegs.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
if [ $? -ne 0 ]
then
   echo "Error Compiling, abort!"
   exit 1
fi

echo "Compiling encoder.c"
gcc -c encoder.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
if [ $? -ne 0 ]
then
   echo "Error Compiling, abort!"
   exit 1
fi

echo "Compiling velocity_state.c"
gcc -c velocity_state.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
if [ $? -ne 0 ]
then
   echo "Error Compiling, abort!"
   exit 1
fi

echo "Compiling http_io.c"
gcc -c http_io.c -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads/ -I/opt/vc/include/interface/vmcs_host/linux/
if [ $? -ne 0 ]
then
   echo "Error Compiling, abort!"
   exit 1
fi

echo "Linking files..."
gcc -o sleipnir-pod *.o -L/opt/vc/lib -lvcos -lbcm_host -lturbojpeg -lcurl -lpthread -lmmal_core -lmmal -lmmal_components -lmmal_util -llog4c
if [ $? -ne 0 ]
then
   echo "Error Linking, abort!"
   exit 1
fi

